sudo: required

language: Go

arch: 
    - amd64
    - arm64
services:
  - docker
jobs:
  include:
  - arch : amd64
    script:
        - apt-get install golang-go
        - make check
        - make -C smoke_tests
  - arch : arm64
    script:
        - apt-get install golang-go
        - make check
        - make -C smoke_tests
script:
  - docker pull alpine:latest
  - chmod 777 docker_run.sh  
  - bash ./docker_run.sh 

